path: /Face-Mask-1 # dataset root dir

train: train/images  # train images (relative to 'path')
test: test/images # test images (relative to 'path')
val: valid/images  # val images (relative to 'path')

# Classes
nc: 7
names:
  0: cloth
  1: kn95
  2: mask_weared_incorrect
  3: n95
  4: surgical
  5: with_mask
  6: without_mask